🔀 :: TookTextField 디자인 시스템
GSM-MSG/Took-iOS pull request #44
Opened 2022-09-11 12:19 UTC by kimsh153

## 개요
TookTextField 디자인 시스템

## 작업사항
TookTextField 디자인 시스템을 개발하였습니다
<img width="306" alt="스크린샷 2022-09-11 오후 9 18 28" src="https://user-images.githubusercontent.com/81547954/189527104-173ea1a4-d3c5-4558-962f-37f19b977fc1.png">

## 사용방법
TookTextField(다양한거 입력)

## 기타

2022-09-11 13:16 UTC, baekteun requested changes

2022-09-11 13:16 UTC, baekteun commented on Projects/UsertInterfaces/DesignSystem/Sources/TextField/TookTextField.swift
> +    ) {
initializer 순서가 좀 안좋은거같네요.. 자주 쓰는 거를 우선순위로 둬서 올려주세요.

2022-09-11 13:16 UTC, baekteun commented on Projects/UsertInterfaces/DesignSystem/Sources/TextField/TookTextField.swift
> +    @FocusState var ifFocus: Bool
ifFocus는 주로 쓰는 단어라기엔 그러니 isFocus나 아예 focusState 어떤지요

2022-09-11 13:16 UTC, baekteun commented on Projects/UsertInterfaces/DesignSystem/Sources/TextField/TookTextField.swift
> +    @FocusState var ifFocus: Bool
그리고 다른 property들과 달리 외부의 영향을 받지 않으니 다른 property들보다 가자 아래에 두는게 좋을거같네요

2022-09-11 13:16 UTC, baekteun commented on Projects/UsertInterfaces/DesignSystem/Sources/TextField/TookTextField.swift
> +    var textFieldHeader: String
header보다는 label 어떤지요?

2022-09-11 13:16 UTC, baekteun commented on Projects/UsertInterfaces/DesignSystem/Sources/TextField/TookTextField.swift
> +    var textFieldHeader: String
그리고 property에 해당 struct의 이름이 들어가는건 좀 어색한거같네요 headerText나 labelText로 수정해주세요

2022-09-11 13:16 UTC, baekteun commented on Projects/UsertInterfaces/DesignSystem/Sources/TextField/TookTextField.swift
> +    var placeHolderText: String
placeholder는 `placeholder` 그 자체가 한 단어 입니다. place + holder의 placeholder가 아니니까요

2022-09-11 13:16 UTC, baekteun commented on Projects/UsertInterfaces/DesignSystem/Sources/TextField/TookTextField.swift
> +
이걸 안 감싸 놓으면 View가 3개가 생기는데요..?

2022-09-11 13:16 UTC, baekteun commented on Projects/UsertInterfaces/DesignSystem/Sources/TextField/TookTextField.swift
> +
그리고 VStack으로 감싸서 alignment: .leading으로 해서 HStack 쓰지 말죠

2022-09-11 13:16 UTC, baekteun commented on Projects/UsertInterfaces/DesignSystem/Sources/TextField/TookTextField.swift
> +                    )
이거 그냥 `.padding(.leading, 10)` 하면 됩니다

2022-09-11 13:16 UTC, baekteun commented on Projects/UsertInterfaces/DesignSystem/Sources/TextField/TookTextField.swift
> +        _ placeHolderText: String = "",
_ 을 가진 파라미터 레이블이 2개이상이면 textFieldHeader는 기본값을 두고 placeholderText를 바꾸고 싶을 때 못 바꿀 수 있으니 많은 Default 값을 가진 파라미터를 가진 initialzer에는 _는 가장 앞 하나에만 쓰는게 좋을거같습니다..

2022-09-12 05:02 UTC, baekteun commented on Projects/UsertInterfaces/DesignSystem/Sources/TextField/TookTextField.swift
> +                .padding(.leading, 10)
padding을 한 이유가 있나요? 디자인상 같은 leading이던데

2022-09-12 05:02 UTC, baekteun commented on Projects/UsertInterfaces/DesignSystem/Sources/TextField/TookTextField.swift
> +    }
```suggestion
    public init(
        _ textFieldHeader: String = "",
        placeholderText: String = "",
        isError: Bool = false,
        errorText: String = "",
        text: Binding<String>,
        buttonAction: @escaping () -> Void = {},
        onCommit: @escaping () -> Void = {}
    ) {
        self.labelText = textFieldHeader
        self.placeholderText = placeholderText
        self.isError = isError
        self.errorText = errorText
        self.buttonAction = buttonAction
        self.onCommit = onCommit
        self._text = text
    }
```
placeHolder -> placeholder 수정합니다

2022-09-12 05:02 UTC, baekteun commented on Projects/UsertInterfaces/DesignSystem/Sources/TextField/TookTextField.swift
> +        self.labelText = textFieldHeader
```suggestion
    public init(
        _ labelText: String = "",
        placeHolderText: String = "",
        isError: Bool = false,
        errorText: String = "",
        text: Binding<String>,
        buttonAction: @escaping () -> Void = {},
        onCommit: @escaping () -> Void = {}
    ) {
        self.labelText = labelText
```
Property명이랑 일체화

2022-09-12 05:02 UTC, baekteun commented on Projects/UsertInterfaces/DesignSystem/Sources/TextField/TookTextField.swift
> +                .modifier(PlaceholderStyle( placeholder: placeholderText))
```suggestion
                .modifier(PlaceholderStyle(placeholder: placeholderText))
```
불필요한 공백 제거

2022-09-12 05:02 UTC, baekteun commented on Projects/UsertInterfaces/DesignSystem/Sources/TextField/TookTextField.swift
> +            if isError == true {
```suggestion
            if isError {
```
불필요한 코드 수정

2022-09-12 05:02 UTC, baekteun commented on Projects/UsertInterfaces/DesignSystem/Sources/TextField/TookTextField.swift
> +        buttonAction: @escaping () -> Void = {},
근데 buttonAction은 쓰는데가 없는데 왜 받는지요?

2022-09-12 05:02 UTC, baekteun commented on Projects/UsertInterfaces/DesignSystem/Sources/TextField/TookTextField.swift
> +        onCommit: @escaping () -> Void = {}
labelText -> placeholder -> text -> isError -> errorText -> onCommit 
순서 어떤지요? labelText -> placeholder -> text는 SwiftUI 의 TextField의 initializer를 따라서 했고 onCommit은 Swift의 trailing closure특성을 이용하기 위해서 가장 뒤로 두었습니다.

2022-09-12 05:05 UTC, kimsh153 commented on Projects/UsertInterfaces/DesignSystem/Sources/TextField/TookTextField.swift
> +                .padding(.leading, 10)
디자인으로 봤을때 약간 띄어져있는거 같아 구현했었습니다 근데 다시보니 아닌거 같네요 수정했습니다

2022-09-12 05:17 UTC, baekteun approved these changes

2022-09-12 05:54 UTC, merged