🔀 :: 명함 교환 페이지
GSM-MSG/Took-iOS pull request #66
Opened 2022-09-26 11:55 UTC by kimsh153

## 개요
명함 교환 페이지

## 작업사항
명함 교환 페이지 제가
<img src="https://user-images.githubusercontent.com/81547954/192269744-89a7f7fa-cfc7-46d0-8004-a8260cd2f77a.png" width="300">

## 기타

2022-09-26 13:13 UTC, baekteun approved these changes

2022-09-26 13:22 UTC, kimsh153 commented on Projects/Features/NewCardFeature/Sources/NewCardView.swift
> +
```suggestion

```

2022-09-26 13:22 UTC, kimsh153 commented on Projects/Features/NewCardFeature/Sources/NewCardView.swift
> +
```suggestion

```

2022-09-26 13:23 UTC, kimsh153 commented on Projects/Features/NewCardFeature/Sources/NewCardView.swift
> +    }
```suggestion
    }
    
```

2022-09-26 14:40 UTC, baekteun commented
backButton configure 해주세요

2022-09-26 14:41 UTC, baekteun requested changes

2022-09-26 14:41 UTC, baekteun commented on Projects/Features/NewCardFeature/Sources/NewCardView.swift
> +    }
backButton도 config해주세요

2022-09-29 13:12 UTC, kimsh153 commented on Projects/Features/NewCardFeature/Sources/NewCardView.swift
> +    }
확인점

2022-09-29 13:13 UTC, baekteun requested changes

2022-09-29 13:13 UTC, baekteun commented on Projects/Features/NewCardFeature/Sources/NewCardView.swift
> +
얘 뭐임

2022-09-29 13:17 UTC, kimsh153 commented on Projects/Features/NewCardFeature/Sources/NewCardView.swift
> +
asdkfhjsaofsd;ojfdiaosjfis

2022-09-29 13:18 UTC, baekteun approved these changes

2022-09-29 13:18 UTC, merged